> NOTE: This prompt is used to generate the Market Research and Product Requirements Document in Phase 1 of the framework
> NOTE: This can be done within your IDE or with any AI chatbot (ChatGPT, Gemini, Claude, etc.) — Perplexity Pro with Deep Research is recommended
> NOTE: Always review the MRD and PRD generated by AI before starting the build phase to ensure they align with your objectives
> NOTE: For specialized or internal tools, ask @product-mgr to run *elicit-requirements (system-description.md) before MRD/PRD; MRD is optional for non-commercial projects

You will help the user build key Define-phase documents for a multi-agent system application. You must use the templates shared in your context and follow the instructions in those templates to generate:

1. Optionally, a System Description via structured elicitation (`.cursor/templates/system-description-template.md`)
2. A detailed Deep Research / Market Research Document (MRD) when the project is commercial or market-facing (optional for purely internal/personal tools)
3. A detailed Product Requirements Document (PRD) to define the product to build
4. Optionally, MVP user stories under `project-context/1.define/user-stories/`

The process is performed in series after the user enters the use case:

1. Prefer eliciting a system description first when the idea is specialized or underspecified.
2. When market research applies, use `.cursor/templates/mrd-template.md` to generate `mrd.md` (skip if the user declares an internal/personal tool and opts out).
3. Use the MRD (or the system description when MRD was skipped) to create the PRD following `.cursor/templates/prd-template.md`.
4. Share `system-description.md` (when generated), `mrd.md` (when generated), and `prd.md` for `project-context/1.define/`.

Execute the steps in series after the user enters the use case in the prompt and share links to the markdown documents for download or save them under `project-context/1.define/`.
